### ISSUE TITLE
Pull Request failed 

### ISSUE THREAD

**Issue by dk172923** [do-community/cloud_haiku#2882]
When I try to pull request I am getting error. Can anyone resolve this for me or atleast figure out what was the issue. 

Run npm test

> cloud_haiku@1.0.0 test
> tap test.js -R min --no-coverage-report --timeout=300

/home/runner/work/cloud_haiku/cloud_haiku/node_modules/append-transform/index.js:62
			hook(module, filename);
   ^
/home/runner/work/cloud_haiku/cloud_haiku/node_modules/append-transform/index.js:1
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/cloud_haiku/cloud_haiku/node_modules/remark/index.js not supported.
Instead change the require of index.js in null to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/runner/work/cloud_haiku/cloud_haiku/node_modules/append-transform/index.js:62:[4](https://github.com/do-community/cloud_haiku/actions/runs/6375687714/job/17301730541?pr=2881#step:5:5))
    at Object.<anonymous> (/home/runner/work/cloud_haiku/cloud_haiku/test.js:3:16)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/home/runner/work/cloud_haiku/cloud_haiku/node_modules/append-transform/index.js:62:4)
    at runMain (/home/runner/.node-spawn-wrap-180[5](https://github.com/do-community/cloud_haiku/actions/runs/6375687714/job/17301730541?pr=2881#step:5:6)-b[6](https://github.com/do-community/cloud_haiku/actions/runs/6375687714/job/17301730541?pr=2881#step:5:7)e39d9be42c/node:68:10)
    at Function.<anonymous> (/home/runner/.node-spawn-wrap-1805-b6e39d9be42c/node:1[7](https://github.com/do-community/cloud_haiku/actions/runs/6375687714/job/17301730541?pr=2881#step:5:8)1:5)
    at Object.<anonymous> (/home/runner/work/cloud_haiku/cloud_haiku/node_modules/nyc/bin/wrap.js:27:4)
    at Generator.next (<anonymous>)
    at /home/runner/.node-spawn-wrap-1[8](https://github.com/do-community/cloud_haiku/actions/runs/6375687714/job/17301730541?pr=2881#step:5:9)05-b6e3[9](https://github.com/do-community/cloud_haiku/actions/runs/6375687714/job/17301730541?pr=2881#step:5:10)d9be42c/node:[17](https://github.com/do-community/cloud_haiku/actions/runs/6375687714/job/17301730541?pr=2881#step:5:18)8:8
    at Object.<anonymous> (/home/runner/.node-spawn-wrap-[18](https://github.com/do-community/cloud_haiku/actions/runs/6375687714/job/17301730541?pr=2881#step:5:19)05-b6e39d9be42c/node:181:3)
    at Generator.next (<anonymous>)

  0 passing (1s)
  1 failing

  1) test.js test.js:
     test.js
  

Error: Process completed with exit code 1.

**Comment by dk172923** [comment]
What should I do from my side?

**Comment by Amarelfaith** [comment]
This is the issue everyone is having

**Comment by ltagliaferri** [comment]
The GitHub Actions is not working right now, don't worry about it 😄
